project_id = "ognlzlciuhzeemifvrts"

[functions.shotstack-render]
verify_jwt = false

[functions.admin-gemini]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.ai-moderator]
verify_jwt = false

[functions.generate-zego-token]
verify_jwt = false
